spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2ze4nabxe8ktlt2dso.mysql.rds.aliyuncs.com:3306/xmt_yueting
    username: root
    password: Aptx4869
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


