server:
  port: 8081
girl:
  cupSize: F
  age: 18


三、职位要求：
1. 有扎实的html5,css3,es6基础。
1. 有jquery,ajax,json使用经验。
1. 熟悉任意JS框架加分，如Vue,React.
1. 熟悉模板引擎加分，如freemarker,Thymeleaf.
1. 2019年毕业，实习能保证至少每周4天。
1. 具备良好的学习能力和分析解决问题能力。
1. 责任心强，良好的对外沟通和团队协作能力，乐于交流和分享。

